agile:
  kaptcha:
    enable: true
    live-time: 30s
    properties:
      kaptcha:
        background:
          clear:
            from: 45,45,45
            to: 45,45,45
        border: 'yes'
        border.color: white
        image:
          height: 45
          width: 125
        noise:
          color: white
        obscurificator:
          impl: com.google.code.kaptcha.impl.ShadowGimpy
        textproducer:
          char:
            length: 4
          font:
            color: white
            names: '"微软雅黑"'
            size: 40
          impl: cloud.agileframework.kaptcha.kaptcha.AgileTextProducer
    token-header: V-CODE
    url: /code